spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel5.cloudtype.app:30515/mvp_daon
    username: mvpuser
    password: mvppassword

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false