spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mvp_daon
    username: mvpuser
    password: mvppassword

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false